config/routes.rb
Rails.application.routes.draw do
  root 'estimates#index'
  # get "/panel", to: "estimates#index", as: 'panel-presupuesto'
  # get "/nuevo-presupuesto", to: "estimates#new", as: 'nuevo-presupuesto'
  # post "/presupuesto", to: "estimates#create", as: 'presupuesto'
  resources :estimates do
    resources :estimate_steps
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/commune.rb
class Commune < ApplicationRecord
  has_many :estimates
end

app/models/plan.rb
class Plan < ApplicationRecord

  has_many :estimates

  #enums
  enum cofre: {'Valparaiso' => 1, 'Coyhaique'=> 2, 'Torres del paine' => 3}
  enum capilla: {'Torneada eléctrica' => 1, 'Torneada cirios' => 2, 'Raulí cirios' => 3}
  enum cubre_urnas: {Pequeño: 1, Mediano: 2 ,Grande: 3, Premium: 4}
  enum cafeteria: {Básico: 1, Estandar: 2, VIP: 3}
  enum tipo_de_anfora: {Tradicional: 1, Elección: 2}
end

app/models/service.rb
class Service < ApplicationRecord

  has_many :estimates

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_estimate

  def current_estimate
    Estimate.find(params[:estimate_id])
  end

end

app/controllers/estimate_steps_controller.rb
class EstimateStepsController < ApplicationController
  # before_action :set_estimate
  include Wicked::Wizard

  require 'sendgrid-ruby'
  include SendGrid

  steps :step_one, :step_two

  def show
    @plans = Plan.all
    @basic_plan = Plan.find_by(name:'Austero')
    @estimate_form = current_estimate

    case step
    when :step_one
      skip_step if @estimate_form.destino_repatriacion.present?
    end
      render_wizard 
  end

  def update
    @estimate_form = current_estimate
    @estimate_form.update(estimate_params)
    redirect_to_finish_wizard
    @estimate_form.update(estimate_number: DateTime.now.strftime('%Y%m%d%H%M%S'), submit: true)
    if @estimate_form.plan_id.present?
      EstimateMailer.with(estimate: @estimate_form).send_estimate_email.deliver_later 
    else
      EstimateMailer.with(estimate: @estimate_form).send_estimate_email_repatriacion.deliver_later 
    end
  end



  private 

  def set_estimate
    @estimate_form = current_estimate
  end

  def redirect_to_finish_wizard
    notice_msg = @estimate_form.destino_repatriacion.present? ? "¡Tu cotización ha sido creada!, próximamente un ejecutivo se pondrá en contacto." : "¡Tu cotización ha sido creada!, próximamente llegará un email con los detalles." 
    redirect_to root_url, notice: notice_msg
  end

  def estimate_params
    params.require(:estimate).permit(:service_id, :plan_id, :client_name, :client_lastname, :client_phone, :client_email, :is_velatorio, :commune_id, :destino_repatriacion, :estimate_number, :submit)
  end

end

app/controllers/estimates_controller.rb
class EstimatesController < ApplicationController
  def index
    @services = Service.all

  end
  
  def new
    @estimate_form = Estimate.new
    @communes = Commune.all
    params[:is_velatorio] = true unless params[:is_velatorio].present?
  end

  def create
    @estimate_form = Estimate.new(estimate_params)
    if @estimate_form.save
      if params[:from_options].present?
          EstimateMailer.with(estimate: @estimate_form).send_estimate_email_opciones.deliver_later
          redirect_to root_path, notice: "Gracias por proveernos tu información, nos contactaremos contigo lo antes posible."
      else
          redirect_to estimate_estimate_steps_path(estimate_id: @estimate_form.id, service_id: params[:service_id])
      end
    end
  end

  private 

  def estimate_params
    params.require(:estimate).permit(:service_id, :plan_id, :client_name, :client_lastname, :client_phone, :client_email, :is_velatorio, :commune_id, :origen_repatriacion, :destino_repatriacion, :estimate_number, :submit)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/estimate_steps_helper.rb
module EstimateStepsHelper
  
end

app/helpers/estimates_helper.rb
module EstimatesHelper
end

app/views/estimate_steps/_basic_plan_table.html.erb
<div class="basic_plan_table mx-auto" >
  <table class="table table-light box-shadow">
    <thead>
      <tr>
        <th scope="col">Seleccionar</th>
        <th scope="col" class="text-center text-secondary"><%=@basic_plan.name %></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row">Cofre</th>
        <td class="text-center text-secondary"><%=link_to "#", "data-toggle": "modal", "data-target": "#exampleModal1" do%>
          <span><%=@basic_plan.cofre%></span>
          <%end%>
          <%= render partial: "modal_cofre", locals: {cofre_name: @basic_plan.cofre.downcase}%>
        </td>

      </tr>
      <tr>
        <th>Capilla</th>
        <td class="text-center text-secondary"><%=@basic_plan.capilla %></td>
      </tr>
      <tr>
        <th>Cruz</th>
        <td class="text-center text-secondary">
          <% if @basic_plan.cruz == true %>
            <i class="far fa-check-circle fa-2x main-green"></i>
          <% else %>
            <i class="far fa-times-circle fa-2x text-danger"></i>
          <% end %>
        </td>
      </tr>
      <tr>
        <th>Sala Velatoria</th>
        <td class="text-center text-secondary">
          <% if @basic_plan.sala_velatoria == true %>
            <i class="far fa-check-circle fa-2x main-green"></i>
          <% else %>
            <i class="far fa-times-circle fa-2x text-danger"></i>
          <% end %>
        </td>
      </tr>
      <tr>
        <th>Flores</th>
        <td class="text-center text-secondary">
          <% if @basic_plan.flores == true %>
            <i class="far fa-check-circle fa-2x main-green"></i>
          <% else %>
            <i class="far fa-times-circle fa-2x text-danger"></i>
          <% end %>
        </td>
      </tr>
      <tr>
        <th>Libro de Condolencias</th>
        <td class="text-center text-secondary">
          <% if @basic_plan.libro_de_condolencias == true %>
            <i class="far fa-check-circle fa-2x main-green"></i>
          <% else %>
            <i class="far fa-times-circle fa-2x text-danger"></i>
          <% end %>
        </td>
      </tr>
      <tr>
        <th>Tarjeta de Condolencias</th>
        <td class="text-center text-secondary">
          <% if @basic_plan.tarjeta_de_condolencias == true %>
            <i class="far fa-check-circle fa-2x main-green"></i>
          <% else %>
            <i class="far fa-times-circle fa-2x text-danger"></i>
          <% end %>
        </td>
      </tr>

      <tr>
        <th>Cubre Urnas</th>
        <td class="text-center text-secondary"><%=@basic_plan.cubre_urnas %></td>
      </tr>
      
      <tr>
        <th>Pie de Urnas</th>
        <td class="text-center text-secondary">
          <% if @basic_plan.pie_de_urnas == true %>
            <i class="far fa-check-circle fa-2x main-green"></i>
          <% else %>
            <i class="far fa-times-circle fa-2x text-danger"></i>
          <% end %>
        </td>
      </tr>

      <tr>
        <th>Medico</th>
        <td class="text-center text-secondary">
          <% if @basic_plan.medico == true %>
            <i class="far fa-check-circle fa-2x main-green"></i>
          <% else %>
            <i class="far fa-times-circle fa-2x text-danger"></i>
          <% end %>
        </td>
      </tr>

      <tr>
        <th>Inscripcion Registro Civil</th>
        <td class="text-center text-secondary">
          <% if @basic_plan.inscripcion_registro_civil == true %>
            <i class="far fa-check-circle fa-2x main-green"></i>
          <% else %>
            <i class="far fa-times-circle fa-2x text-danger"></i>
          <% end %>
        </td>
      </tr>

      <tr>
        <th>Tramites Legales</th>
        <td class="text-center text-secondary">
          <% if @basic_plan.tramites_legales == true %>
            <i class="far fa-check-circle fa-2x main-green"></i>
          <% else %>
            <i class="far fa-times-circle fa-2x text-danger"></i>
          <% end %>
        </td>
      </tr>

      <tr>
        <th>Carroza Panoramica</th>
        <td class="text-center text-secondary"><%=@basic_plan.carroza_panoramica %></td>
      </tr>

      <tr>
        <th>Van de Acompañamiento</th>
        <td class="text-center text-secondary"><%=@basic_plan.van_de_acompanamiento %></td>
      </tr>
      <tr>
        <th>Cinta de Identificacion</th>
        <td class="text-center text-secondary">
          <% if @basic_plan.cinta_de_identificacion == true %>
            <i class="far fa-check-circle fa-2x main-green"></i>
          <% else %>
            <i class="far fa-times-circle fa-2x text-danger"></i>
          <% end %>
        </td>
      </tr>

      <tr>
        <th>Cafeteria</th>
        <td class="text-center text-secondary"><%=@basic_plan.cafeteria %></td>
      </tr>

      <tr>
        <th>Obituario Virtual</th>
        <td class="text-center text-secondary">
          <% if @basic_plan.obituario_virtual == true %>
            <i class="far fa-check-circle fa-2x main-green"></i>
          <% else %>
            <i class="far fa-times-circle fa-2x text-danger"></i>
          <% end %>
        </td>
      </tr>

      <tr>
        <th>Obituario Mercucio</th>
        <td class="text-center text-secondary">
          <% if @basic_plan.obituario_mercucio == true %>
            <i class="far fa-check-circle fa-2x main-green"></i>
          <% else %>
            <i class="far fa-times-circle fa-2x text-danger"></i>
          <% end %>
        </td>
      </tr>

      <tr>
        <th>Homenaje Presencial</th>
        <td class="text-center text-secondary">
          <% if @basic_plan.homenaje_presencial == true %>
            <i class="far fa-check-circle fa-2x main-green"></i>
          <% else %>
            <i class="far fa-times-circle fa-2x text-danger"></i>
          <% end %>
        </td>
      </tr>

      <tr>
        <th>Video de Homenaje</th>
        <td class="text-center text-secondary">
          <% if @basic_plan.video_de_homenaje == true %>
            <i class="far fa-check-circle fa-2x main-green"></i>
          <% else %>
            <i class="far fa-times-circle fa-2x text-danger"></i>
          <% end %>
        </td>
      </tr>

      <tr>
        <th>Tipo de Anfora</th>
        <td class="text-center text-secondary"><%=@basic_plan.tipo_de_anfora %></td>
      </tr>

      <tr>
        <th>Precio</th>
        <td class="text-center text-secondary"><%= number_to_currency(@basic_plan.precio, delimiter: ".", precision: 0) %></td>
      </tr>

      
      <tr>
        <th></th>

        <td class="text-center text-secondary"><%= link_to 'Seleccionar', next_wizard_path(plan_id: @basic_plan.id,step: 3), :class => 'btn bg-main-green text-light select-plan',estimate_id: @estimate_form.id %></td>
      </tr>
    </tbody>
  </table>
</div>

app/views/estimate_steps/_modal_cofre.html.erb
<div class="modal fade" id="exampleModal1" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title text-center" id="exampleModalLabel">Cofre</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= image_tag("#{cofre_name}.jpg") %>
      </div>
    </div>
  </div>
</div>

app/views/estimate_steps/step_one.html.erb
<div class="container py-4 mb-3">
  <%  if @estimate_form.errors.any?  %>
    <div class="error_messages">
      <h2><%= pluralize(@estimate_form.errors.count, "error") %> prohibe que esta cotización sea realizada:</h2>
      <ul>
        <%= @estimate_form.errors.full_messages.each do |message| %>
          <%= message %>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= params[:step] %>
  <div class="decoration-line mb-2"></div>
  <h2 class="main-green"> Opciones </h2>  
  <%= form_for @estimate_form, url: wizard_path do |f| %>
    <%= hidden_field_tag :estimate_id, @estimate_form.id %>
    <p class="text-secondary">Para un servicio como el que solicitas disponemos de las siguientes opciones. Selecciona la que más se ajuste a tu necesidad.</p>
    <div class="mb-3">
      <%= render 'table' %>
      <div class="text-center py-3 ">
        <%= link_to 'Volver', new_estimate_path(service_id: @estimate_form.service_id, service_name: @estimate_form.service.name ), :class => 'btn bg-main-green text-light px-20' %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/estimate_steps/step_two.html.erb
<div class="container py-4 mb-3">
  <div class="decoration-line mb-2"></div>
  <h2 class="main-green"> Opciones </h2>  
  <%= form_for @estimate_form, url: wizard_path do |f| %>
    <%= f.hidden_field :plan_id, value: params[:plan_id] if params[:plan_id].present? %>
    <%= hidden_field_tag :estimate_id, @estimate_form.id %>
    <%= f.hidden_field :service_id, value: @estimate_form.service_id %>
    <div class="mb-3 ">
      <h5 class="text-secondary"> Has indicado que deseas recibir presupuesto para este servicio</h5>
      <div class="row">
        <div class="box-shadow my-5 py-4 col-md-6 contact_form bg-urgency">
          <div class="card-body text-left text-secondary">
            <div class="form-row">
              <div class="form-group col-md-6">
                <%= hidden_field_tag :from_options, true %>
                <label for="inputEmail4">Nombre</label>
                <%= f.text_field :client_name, class:"form-control"  %>
              </div>
              <div class="form-group col-md-6">
                <label for="inputPassword4">Apellido</label>
                <%= f.text_field :client_lastname, class:"form-control"  %>
              </div>
            </div>
            <div class="form-row">
              <div class="form-group col-md-6">
                <label for="inputEmail4">Tu teléfono de contacto</label>
                <%= f.text_field :client_phone, class:"form-control"  %>
              </div>
              <div class="form-group col-md-6">
                <label for="inputPassword4">Tu correo electrónico</label>
                <%= f.text_field :client_email, class:"form-control"  %>
              </div>
            </div>
          </div>
        </div>
        <div class="my-5 col-md-5 py-4 ">
          <div class="card-body text-left text-secondary row">
            <div class="col-md-6">
              <i class="fas fa-user-friends fa-8x main-green"></i>
            </div>
            <div class="col-md-6 ">
              <small>LLÁMANOS AL</small>
              <h5>+569 3187 9315</h5>
              <p>Atención inmediata 24 horas</p>
            </div>
          </div>
        </div>
      </div>
      <div class="text-center">
        <%= recaptcha_tags %>
        <%= link_to 'Volver', new_estimate_path(service_id: @estimate_form.service_id, service_name: @estimate_form.service.name ), :class => 'btn bg-main-green text-light px-20' %>
        <%= f.submit 'Solicitar presupuesto', :class => 'btn bg-main-green text-light px-20 submit-form',disabled: true %>
      </div>
    </div>
  </div>
  <% end %>
</div>

<script>

  document.getElementById("estimate_client_name").addEventListener("change",function(){
    let name = document.getElementById("estimate_client_name").value;
    let lastname = document.getElementById("estimate_client_lastname").value;
    let phone = document.getElementById("estimate_client_phone").value;
    let email = document.getElementById("estimate_client_email").value;
    let submit = document.getElementsByClassName("submit-form");
    if (name != '' && lastname != '' && phone != '' && email != '') {
      submit[0].removeAttribute("disabled");
    } else {
      submit[0].setAttribute("disabled", true)
    }
  })

  document.getElementById("estimate_client_lastname").addEventListener("change",function(){
    let name = document.getElementById("estimate_client_name").value;
    let lastname = document.getElementById("estimate_client_lastname").value;
    let phone = document.getElementById("estimate_client_phone").value;
    let email = document.getElementById("estimate_client_email").value;
    let submit = document.getElementsByClassName("submit-form");
    if (name != '' && lastname != '' && phone != '' && email != '') {
      submit[0].removeAttribute("disabled");
    } else {
      submit[0].setAttribute("disabled", true)
    }
  })

  document.getElementById("estimate_client_phone").addEventListener("change",function(){
    let name = document.getElementById("estimate_client_name").value;
    let lastname = document.getElementById("estimate_client_lastname").value;
    let phone = document.getElementById("estimate_client_phone").value;
    let email = document.getElementById("estimate_client_email").value;
    let submit = document.getElementsByClassName("submit-form");
    if (name != '' && lastname != '' && phone != '' && email != '') {
      submit[0].removeAttribute("disabled");
    } else {
      submit[0].setAttribute("disabled", true)
    }
  })

  document.getElementById("estimate_client_email").addEventListener("change",function(){
    let name = document.getElementById("estimate_client_name").value;
    let lastname = document.getElementById("estimate_client_lastname").value;
    let phone = document.getElementById("estimate_client_phone").value;
    let email = document.getElementById("estimate_client_email").value;
    let submit = document.getElementsByClassName("submit-form");
    if (name != '' && lastname != '' && phone != '' && email != '') {
      submit[0].removeAttribute("disabled");
    } else {
      submit[0].setAttribute("disabled", true)
    }
  })

  document.getElementById("recaptcha-anchor").addEventListener("change",function(){
    alert("hola")
  })
</script>

app/views/estimates/estimate_pdf_opciones.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FunerariaProjectManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet"
    href="https://use.fontawesome.com/releases/v5.6.3/css/all.css"
    integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/ "crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= image_tag wicked_pdf_asset_base64("logo.jpeg"), size: '180x90' %>
    <h1 class="text-muted text-center">Funeraria Ivan Martinez</h1>
    <div class="py-3">
      <h2 class="font-weight-bolder text-center pb-3 mb-3"> Consulta </h2>
    </div>

    <div class="container mt-3">
      <table class="table table-bordered">
        <tbody>
          <tr>
            <td>Nombre cliente:</td>
            <td colspan="2"><%= "#{@estimate.client_name} #{@estimate.client_lastname}" %></td>
          </tr>
          <tr>
            <td>Teléfono:</td>
            <td colspan="2"><%= @estimate.client_phone %></td>
          </tr>
          <tr>
            <td>Email:</td>
            <td colspan="2"><%= @estimate.client_email %></td>
          </tr>
          <tr>
            <td>Plan:</td>
            <td class="font-weight-bolder" colspan="2"><%= @estimate.service.name %></td>
          </tr>
        </tbody>
      </table>
    </div>
    
    <%= render 'generals/footer' %>
  
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" crossorigin="anonymous"></script>

  </body>
</html>

app/views/estimates/estimate_pdf_repatriacion.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FunerariaProjectManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet"
    href="https://use.fontawesome.com/releases/v5.6.3/css/all.css"
    integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/ "crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <table class="table table-borderless">
      <tbody>
        <tr>
          <th scope="col">
            <%= image_tag wicked_pdf_asset_base64("logo.jpeg"), size: '200x110' %>
          </th>
          <th scope="col">
            <h1 class="text-center text-success font-weight-bold">Funeraria Ivan Martinez</h1>
          </th>
          <th scope="col" class="text-right">
            <h4 class="text-secondary">Cotización ref.</h4>
            <h4 class="text-secondary"><%=@estimate.estimate_number %></h4>
          </th>
        </tr>
      </tbody>
    </table>
    <div class="py-3">
      <h2 class="font-weight-bolder text-center pb-3 mb-3"> Presupuesto </h2>
    </div>

    <div class="container mt-3">
      <table class="table table-bordered">
        <tbody>
          <tr>
            <td>Nombre cliente:</td>
            <td colspan="2"><%= "#{@estimate.client_name} #{@estimate.client_lastname}" %></td>
          </tr>
          <tr>
            <td>Teléfono:</td>
            <td colspan="2"><%= @estimate.client_phone %></td>
          </tr>
          <tr>
            <td>Email:</td>
            <td colspan="2"><%= @estimate.client_email %></td>
          </tr>
          <tr>
            <td>Plan:</td>
            <td class="font-weight-bolder" colspan="2"><%= @estimate.service.name %></td>
          </tr>
        </tbody>
      </table>
    </div>
    
    <h2 class="font-weight-bolder text-center pb-3 mb-3"> Detalles repatriación </h2>

    <table class="table table-bordered box-shadow">
    <tbody>
      <tr>
        <th scope="col">Origen repatriación</th>
        <th scope="col" class="text-center text-secondary"><%= @estimate.origen_repatriacion %></th>
      </tr>
      <tr>
        <th scope="row">Destino repatriación</th>
        <td class="text-center text-secondary"><%= @estimate.destino_repatriacion %></td>
      </tr>
    </tbody>
  </table>

    <%= render 'generals/footer' %>
  
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" crossorigin="anonymous"></script>

  </body>
</html>

app/views/estimates/index.html.erb
<p class=" h5 text-secondary text-center font-italic"> Quiero que la ceremonia sea una...</p>
<div class="card-group container pb-4">
  <% @services.each do |service| %>
    
    <% if service.name == Estimate::CREMACION%>
      <%  image = 'cremacion.jpg'%>
    <% elsif service.name == Estimate::INHUMACION %>
      <%  image = 'inhumacion.jpg'%>
    <% elsif service.name == Estimate::REPATRIACION %>
      <%  image = 'repatriacion.png'%>
    <% elsif service.name == Estimate::OTRAS_OPCIONES %>
      <%  image = 'other_options.jpg'%>
    <% end %>

    <div class="card border-white text-center m-3">
      <%= link_to new_estimate_path(service_id: service.id, service_name: service.name)do %>
        <%= image_tag(image, class: 'card-img-top mt-2') %>
      <% end %>
      <div class="card-body">
        <h5 class="card-title text-secondary"><%= service.name %></h5>
      </div>
    </div>
  <% end %>
  
</div>

<script>
  setTimeout(() => {
    $(".alert-info").hide();
  }, 3000);
</script>

app/views/estimates/new.html.erb
<div class="container py-4 mb-3">
  <div class="decoration-line mb-2"></div>
  <h2 class="main-green"> <%= params[:service_name] == Estimate::OTRAS_OPCIONES ? 'Contacto' : 'Servicio y localidad' %> </h2>  
  <%= form_for @estimate_form, url: estimates_path, method: :post do |f| %>
    <div class="mb-3 ">
      <%= f.hidden_field :service_id, value: params[:service_id] %>
      <% if params[:service_name] == Estimate::CREMACION || params[:service_name] == Estimate::INHUMACION %>
        <%= render 'estimates/partials/no_repatriacion', f: f %>
      <% elsif params[:service_name] == Estimate::REPATRIACION %>
        <%= render 'estimates/partials/repatriacion',f: f %>
      <% else params[:service_name] == Estimate::OTRAS_OPCIONES %> 
        <%= render 'estimates/partials/contact_form',f: f %>
      <% end %>
      
    </div>
  </div>
  <% end %>
</div>

app/views/estimates/partials/_no_repatriacion.html.erb
<div class="form-group row">
  <label class="col-sm-3 col-form-label ">Seleccione comuna</label>
  <div class="col-sm-4">
    <%= f.select :commune_id, options_from_collection_for_select(@communes, :id, :name), {prompt: "Seleccionar comuna"}, { class: 'form-control' } %>
  </div>
</div>
<div class="form-group row">
  <label for="staticEmail" class="col-sm-3 col-form-label">¿Deseas sala de velatorio?
  </label>
  <div class="col-sm-2">
    <div class="form-check form-check-inline">
      <%= f.radio_button :is_velatorio, true, {class: "form-check-input"} %>
      <label class="form-check-label" for="inlineRadio1">Si</label>
    </div>
    <div class="form-check form-check-inline">
      <%= f.radio_button :is_velatorio, false,{class: "form-check-input"} %>
      <label class="form-check-label" for="inlineRadio2">No</label>
    </div>
  </div>
</div>
<div class="text-center my-4">
  <%= link_to 'Volver', root_path, :class => 'btn bg-main-green text-light px-20' %>
  <%= f.submit 'Continuar', :class => 'btn bg-main-green text-light px-20 submit-form', disabled: true %>
</div>

<script>
  document.getElementById("estimate_commune_id").addEventListener("change",function(){
    let selected = document.getElementById("estimate_commune_id").value;
    let submit = document.getElementsByClassName("submit-form");
    if (selected != '') {
      submit[0].removeAttribute("disabled");
    } else {
      submit[0].setAttribute("disabled", true)
    }
  })
</script>

app/views/generals/_footer.html.erb
<footer class="container-fluid bg-black text-secondary pt-2 mt-5">
    <div class="container">
        <div class="text-center">
          © Copyright 2022. Desarrollado Por Funeraria Chile Iván Martínez
        </div>
    </div>
</footer>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Funeraria Ivan Martinez</title>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= wicked_pdf_stylesheet_link_tag "pdf" %>
  </head>
  <body>
    <div id="header">
      <!--= wicked_pdf_image_tag 'thumbnail.png', height: "30", width: "auto"-->
    </div>
    <%= yield %>
  </body>
</html>